/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ozor (https://sketchfab.com/Ozor)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-hammer-026d752a132d48369a4e854af2a5e86b
title: Cartoon hammer
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { Hammering } from "../components/Diglett 0"
var rotateH=0
var isHammer=true;
//해머 내리치는 함수
function hammerRotate(){
    rotateH+=1;
    setTimeout(() => {
      isHammer=false;
      rotateH-=1;
    }, 100);
    rotateH=0;
  }

export default function Model(props) {
  const { nodes, materials } = useGLTF('model/cartoon_hammer.glb')
  const group = useRef();
  const [hammerPos, setPos] = useState({x: 0, y: -0.13, z: 1.08});
  useFrame(()=>{group.current.rotation.z=rotateH;
    if(isHammer){
    hammerRotate();
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[hammerPos.x, hammerPos.y, hammerPos.z]} rotation={[-Math.PI, 0, -0.05]}>
          <mesh geometry={nodes.Marteau_0.geometry} material={materials.Gris} />
          <mesh geometry={nodes.Marteau_1.geometry} material={materials.Marron_clair} />
          <mesh geometry={nodes.Marteau_1_1.geometry} material={materials.Marron_clair} />
          <mesh geometry={nodes.Marteau_2.geometry} material={materials.Jaune} />
        </group>
        <group position={[0, 0, 8.14]} />
      </group>
    </group>
  )
}

useGLTF.preload('model/cartoon_hammer.glb')
