/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: agraphafx (https://sketchfab.com/agraphafx)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ag-craterdeep-001-9b6c2ef587184d60b2ce4c3810f37ac2
title: AG_CraterDeep_001
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hole.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.lambert3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/hole.glb')
